# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('LIMIT_BAL', models.IntegerField()),
                ('SEX', models.IntegerField()),
                ('EDUCATION', models.IntegerField()),
                ('MARRIAGE', models.IntegerField()),
                ('AGE', models.IntegerField()),
                ('PAY_0', models.IntegerField()),
                ('PAY_2', models.IntegerField()),
                ('PAY_3', models.IntegerField()),
                ('PAY_4', models.IntegerField()),
                ('PAY_5', models.IntegerField()),
                ('PAY_6', models.IntegerField()),
                ('BILL_AMT1', models.IntegerField()),
                ('BILL_AMT2', models.IntegerField()),
                ('BILL_AMT3', models.IntegerField()),
                ('BILL_AMT4', models.IntegerField()),
                ('BILL_AMT5', models.IntegerField()),
                ('BILL_AMT6', models.IntegerField()),
                ('PAY_AMT1', models.IntegerField()),
                ('PAY_AMT2', models.IntegerField()),
                ('PAY_AMT3', models.IntegerField()),
                ('PAY_AMT4', models.IntegerField()),
                ('PAY_AMT5', models.IntegerField()),
                ('PAY_AMT6', models.IntegerField()),
                ('default_payment_next_month', models.IntegerField()),
            ],
        ),
    ]
